### ISSUE TITLE
HTML compilation fails when PlantUML is not available

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#541] opened 2021-10-08 05:35 UTC
Reported by OGC @gbuehler

> Using the metanorma build in Gitlab for the T17 ERs, we don't seem to be able to generate image from PlantUML.
> The build will fail on the HTML generation, but generate the PDF (without the PlantUML being converted).

As PlantUML is an optional dependency, not having it installed should not fail Metanorma compilation.

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-cli/issues/254#issuecomment-938357592_

**Comment by ronaldtse** [comment] 2021-10-08 05:35
Maybe a warning is more appropriate here.

**Comment by opoudjis** [comment] 2021-10-08 12:15
There already is a warning being issue. The issue is not standoc at all; if it was, you wouldn't even be getting PDF output. It is isodoc HTML not dealing for some reason with raw PlantUML input. Will try to replicate; if I cannot, I will need OGC to provide me their PlantUML.

**Comment by opoudjis** [comment] 2021-10-12 12:46
If I add `@enduml` at the end, the PlantUML compiles correctly.

The code deals with a missing `@startuml` and `@enduml`; it doesn't deal with a mismatch. I can fix this, but frankly, I think I should not: we don't know why there is a mismatch in the PlantUML source, and whether the missing final line may reflect other missing lines.

**Comment by opoudjis** [comment] 2021-10-12 12:48
I'm going to raise an error if startuml and no enduml instead.

**Comment by opoudjis** [comment] 2021-10-12 14:19
I've tested it with PlantUML not installed, and I'm still getting no such crash on HTML. I'm putting this on hold, I simply cannot replicate it.

**Comment by opoudjis** [comment] 2022-01-31 13:16
I'm closing this, I have no evidence this is a concern any more.

**Closed by opoudjis** 2022-01-31 13:16 UTC
Labels: bug
