### ISSUE TITLE
Nokogiri breaking Mac Travis

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#69] opened 2019-05-05 23:38 UTC
https://travis-ci.org/metanorma/isodoc/jobs/528098826

**Comment by CAMOBAP795** [comment] 2019-05-08 05:02
Looking for solution

**Comment by CAMOBAP795** [comment] 2019-05-09 20:41
The issue is gone after a cache invalidation on Travis

@opoudjis I think we can close this

**Comment by ronaldtse** [comment] 2019-05-11 14:40
@CAMOBAP795 the problem still exists on the builds.

**Comment by CAMOBAP795** [comment] 2019-05-11 14:40
@ronaldtse which ones?

**Comment by ronaldtse** [comment] 2019-05-11 14:44
Sorry it's for `isodoc`. https://travis-ci.org/metanorma/isodoc

<img width="990" alt="Screen Shot 2019-05-11 at 10 43 04 PM" src="https://user-images.githubusercontent.com/11865/57571252-250e4f80-743e-11e9-94ad-1c5f9b5bb244.png">

**Comment by ronaldtse** [comment] 2019-05-11 14:45
And it still exists here in this repo:

https://travis-ci.org/metanorma/metanorma-standoc/jobs/529718774

```
bundle exec rake
/Users/travis/.rvm/rubies/ruby-2.5.5/bin/ruby -I/Users/travis/build/metanorma/metanorma-standoc/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.8.0/lib:/Users/travis/build/metanorma/metanorma-standoc/vendor/bundle/ruby/2.5.0/gems/rspec-support-3.8.0/lib /Users/travis/build/metanorma/metanorma-standoc/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.8.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
An error occurred while loading ./spec/asciidoctor-standoc/base_spec.rb.
Failure/Error: require "nokogiri"
LoadError:
  dlopen(/Users/travis/build/metanorma/metanorma-standoc/vendor/bundle/ruby/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri/nokogiri.bundle, 9): Library not loaded: /Users/travis/.rvm/rubies/ruby-2.5.4/lib/libruby.2.5.dylib
    Referenced from: /Users/travis/build/metanorma/metanorma-standoc/vendor/bundle/ruby/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri/nokogiri.bundle
    Reason: image not found - /Users/travis/build/metanorma/metanorma-standoc/vendor/bundle/ruby/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri/nokogiri.bundle
# ./vendor/bundle/ruby/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri.rb:32:in `require'
# ./vendor/bundle/ruby/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri.rb:32:in `rescue in <top (required)>'
# ./vendor/bundle/ruby/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri.rb:28:in `<top (required)>'
# ./lib/asciidoctor/standoc/base.rb:2:in `require'
# ./lib/asciidoctor/standoc/base.rb:2:in `<top (required)>'
# ./lib/asciidoctor/standoc/converter.rb:3:in `require'
# ./lib/asciidoctor/standoc/converter.rb:3:in `<top (required)>'
# ./lib/metanorma-standoc.rb:2:in `require_relative'
# ./lib/metanorma-standoc.rb:2:in `<top (required)>'
# ./spec/spec_helper.rb:15:in `require'
# ./spec/spec_helper.rb:15:in `<top (required)>'
# ./spec/asciidoctor-standoc/base_spec.rb:1:in `require'
# ./spec/asciidoctor-standoc/base_spec.rb:1:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- nokogiri/2.5/nokogiri
#   ./vendor/bundle/ruby/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri.rb:30:in `require'

```

**Comment by CAMOBAP795** [comment] 2019-05-11 14:45
@ronaldtse according to history https://travis-ci.org/metanorma/isodoc/builds the last one is green, isn't it?

**Comment by ronaldtse** [comment] 2019-05-11 14:46
@CAMOBAP795 you mean it's in a separate branch but not merged to master?

**Comment by CAMOBAP795** [comment] 2019-05-11 14:49
@ronaldtse not actually, Travis keep separate caches per each branch.

I have cleared all caches other branches are "red" because I didn't start building on them yet, let me do this

**Comment by CAMOBAP795** [comment] 2019-05-15 13:32
Done

**Closed by CAMOBAP795** 2019-05-15 13:32 UTC
