### ISSUE TITLE
Math expressions with "|" symbol are not generating well

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#257] opened 2020-04-20 17:20 UTC
From @anermina 

When math expressions include "|" symbol, brackets which come afterwards are not generated. Moreover, matrices which include "|" are not generated properly.
This was noticed while editing ISO 10303-50.

Example with brackets:

Expected:
![image](https://user-images.githubusercontent.com/11865/79707231-51894780-82ee-11ea-8c82-1b7cbee87e50.png)

Generated:
![image](https://user-images.githubusercontent.com/11865/79707233-551cce80-82ee-11ea-8000-3306318d5df4.png)

Example with matrices:

Expected:
![image](https://user-images.githubusercontent.com/11865/79707259-72ea3380-82ee-11ea-95b1-f96948dfc405.png)

Generated:

![image](https://user-images.githubusercontent.com/11865/79707260-78477e00-82ee-11ea-8c72-1ec400924f7d.png)

**Comment by opoudjis** [comment] 2020-04-29 11:36
Ugh.

The problem is that | can act as a delimiter in matrixes, just as { } and ( ) and [ ] can. So when the asciimath parser encounters this, it thinks that the expression started with { ends at |.

This is difficult to address, because of genuine ambiguity.

**Comment by opoudjis** [comment] 2020-04-29 11:50
Asciimath has `:|:` for this case, but it isn't being recognised by the parser. Investigating.

**Comment by opoudjis** [comment] 2020-04-29 12:05
It turns out that this is unreleased functionality.

So:

@anermina, @manuel489 : if you have any AsciiMath that looks like: `{ ... | ... }`  , where curly brackets may be replaced by angle brackets, square brackets, or parentheses, do *not* use `|`, which by default is treated as a bracket itself. Instead, use `:|:` . In the function of "such that", you can always use `:|:` instead of `|`, whether or not there are brackets surrounding. In fact, you should.

The catch is that this was added in October to the asciimath gem, as one of many additions to Asciimath in the JS version of Asciimath (at my request: https://github.com/asciidoctor/asciimath/issues/14), but the gem has not been released with these updates. So you must add

````
gem "asciimath", git: "https://github.com/asciidoctor/asciimath"
````

to the Gemfile of any document you are adding `:|:` to, until https://github.com/asciidoctor/asciimath is updated.

**Closed by opoudjis** 2020-04-29 12:05 UTC
Labels: bug
