### ISSUE TITLE
Unable to compile starting from today because of an error fetching relaton documents

### ISSUE THREAD

**Issue by PeterTKY** [metanorma/metanorma-standoc#99] opened 2019-08-13 03:17 UTC
It's happening in the iso-digital-addressing repo to which you should have access. I copied the error log for the compilation (Please note that the printing of variable ref was added by me):

> fetching ISO 19160-4...
fetching ISO/IEC/IEEE 31320-2...
fetching ISO/IEC 10179...
ref...
"<bibitem type=\"standard\" id=\"ISO19160-1\">\n" +
"  <fetched>2019-08-13</fetched>\n" +
"  <title type=\"title-main\" format=\"text/plain\" language=\"en\" script=\"Latn\"/>\n" +
"  <title type=\"main\" format=\"text/plain\" language=\"en\" script=\"Latn\"/>\n" +
"  <uri type=\"src\">https://www.iso.org/standard/61710.html</uri>\n" +
"  <uri type=\"obp\">https://www.iso.org/obp/ui/#account/products</uri>\n" +
"  <uri type=\"rss\">https://www.iso.org/contents/data/standard/06/17/61710.detail.rss</uri>\n" +
"  <contributor>\n" +
"    <role type=\"publisher\"/>\n" +
"    <organization>\n" +
"      <name>International Organization for Standardization</name>\n" +
"      <abbreviation>ISO</abbreviation>\n" +
"      <uri>www.iso.org</uri>\n" +
"    </organization>\n" +
"  </contributor>\n" +
"  <edition>1</edition>\n" +
"  <language>en</language>\n" +
"  <script><![CDATA[Latn]]></script>\n" +
"  <status>\n" +
"    <stage>60</stage>\n" +
"    <substage>60</substage>\n" +
"  </status>\n" +
"  <copyright>\n" +
"    <from>2015</from>\n" +
"    <owner>\n" +
"      <organization>\n" +
"        <name>ISO</name>\n" +
"      </organization>\n" +
"    </owner>\n" +
"  </copyright>\n" +
"  <relation type=\"instance\">\n" +
"    <bibitem type=\"standard\">\n" +
"      <fetched>2019-08-13</fetched>\n" +
"      <title type=\"title-main\" format=\"text/plain\" language=\"en\" script=\"Latn\"/>\n" +
"      <title type=\"main\" format=\"text/plain\" language=\"en\" script=\"Latn\"/>\n" +
"      <uri type=\"src\">https://www.iso.org/standard/61710.html</uri>\n" +
"      <uri type=\"obp\">https://www.iso.org/obp/ui/#account/products</uri>\n" +
"      <uri type=\"rss\">https://www.iso.org/contents/data/standard/06/17/61710.detail.rss</uri>\n" +
"      <date type=\"published\">\n" +
"        <on>2015</on>\n" +
"      </date>\n" +
"      <contributor>\n" +
"        <role type=\"publisher\"/>\n" +
"        <organization>\n" +
"          <name>International Organization for Standardization</name>\n" +
"          <abbreviation>ISO</abbreviation>\n" +
"          <uri>www.iso.org</uri>\n" +
"        </organization>\n" +
"      </contributor>\n" +
"      <edition>1</edition>\n" +
"      <language>en</language>\n" +
"      <script><![CDATA[Latn]]></script>\n" +
"      <abstract format=\"text/plain\" language=\"en\" script=\"Latn\">ISO 19160-1:2015 defines a conceptual model for address information (address model), together with the terms and definitions that describe the concepts in the model. Lifecycle, metadata, and address aliases are included in the conceptual model. The model is presented in the Unified Modeling Language (UML).The model provides a common representation of address information, independent of actual addressing implementations. It is not intended to replace conceptual models proposed in other specifications, but provides a means to cross-map between different conceptual models for address information and enables the conversion of address information between specifications.The model provides a basis for developing address specifications by individual countries or communities.</abstract>\n" +
"      <status>\n" +
"        <stage>60</stage>\n" +
"        <substage>60</substage>\n" +
"      </status>\n" +
"      <copyright>\n" +
"        <from>2015</from>\n" +
"        <owner>\n" +
"          <organization>\n" +
"            <name>ISO</name>\n" +
"          </organization>\n" +
"        </owner>\n" +
"      </copyright>\n" +
"    </bibitem>\n" +
"  </relation>\n" +
"</bibitem>"
bundler: failed to load command: metanorma (/Users/peter_tam/.rbenv/versions/2.6.0/bin/metanorma)
NoMethodError: undefined method `text' for nil:NilClass
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/metanorma-standoc-c6dd7a384410/lib/asciidoctor/standoc/cleanup_ref.rb:122:in `block in reference_names'
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/node_set.rb:238:in `block in each'
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/node_set.rb:237:in `upto'
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/node_set.rb:237:in `each'
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/metanorma-standoc-c6dd7a384410/lib/asciidoctor/standoc/cleanup_ref.rb:117:in `reference_names'
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/metanorma-standoc-c6dd7a384410/lib/asciidoctor/standoc/cleanup.rb:43:in `cleanup'
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/metanorma-csd-1.2.3/lib/asciidoctor/csd/converter.rb:32:in `makexml'
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/metanorma-csd-1.2.3/lib/asciidoctor/csd/converter.rb:40:in `document'
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/metanorma-standoc-c6dd7a384410/lib/asciidoctor/standoc/utils.rb:101:in `convert'
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:1190:in `convert'
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1521:in `convert'
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/metanorma-0.3.14/lib/metanorma/input/asciidoc.rb:8:in `process'
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/metanorma-csd-1.2.3/lib/metanorma/csd/processor.rb:26:in `input_to_isodoc'
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/metanorma-0.3.14/lib/metanorma/compile.rb:101:in `process_input'
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/metanorma-0.3.14/lib/metanorma/compile.rb:17:in `compile'
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.2.3/lib/metanorma/cli/compiler.rb:23:in `compile_file'
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.2.3/lib/metanorma/cli/compiler.rb:11:in `compile'
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.2.3/lib/metanorma/cli/compiler.rb:15:in `compile'
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.2.3/lib/metanorma/cli/command.rb:34:in `compile'
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.2.3/lib/metanorma/cli.rb:57:in `start'
  /Users/peter_tam/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.2.3/exe/metanorma:20:in `<top (required)>'
  /Users/peter_tam/.rbenv/versions/2.6.0/bin/metanorma:23:in `load'
  /Users/peter_tam/.rbenv/versions/2.6.0/bin/metanorma:23:in `<top (required)>'

**Comment by opoudjis** [comment] 2019-08-13 06:05
Relaton isn't me. Reassigning to @andrew2net.

**Comment by opoudjis** [comment] 2019-08-13 06:19
My crash is earlier on, and elsewhere in the stack:

````
fetching ISO 19160-1...
#<Thread:0x00007f8eb80c0460@/Users/nickn/.rvm/gems/ruby-2.5.1/gems/relaton-bib-0.2.3/lib/relaton_bib/workers_pool.rb:17 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	7: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/relaton-bib-0.2.3/lib/relaton_bib/workers_pool.rb:19:in `block (2 levels) in worker'
	6: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/relaton-iso-0.5.2/lib/relaton_iso/iso_bibliography.rb:85:in `block in fetch_pages'
	5: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/relaton-iso-0.5.2/lib/relaton_iso/hit.rb:22:in `fetch'
	4: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/relaton-iso-0.5.2/lib/relaton_iso/scrapper.rb:61:in `parse_page'
	3: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/relaton-iso-0.5.2/lib/relaton_iso/scrapper.rb:134:in `fetch_titles_abstract'
	2: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/relaton-iso-0.5.2/lib/relaton_iso/scrapper.rb:134:in `each'
	1: from /Users/nickn/.rvm/gems/ruby-2.5.1/gems/relaton-iso-0.5.2/lib/relaton_iso/scrapper.rb:141:in `block in fetch_titles_abstract'
/Users/nickn/.rvm/gems/ruby-2.5.1/gems/relaton-iso-0.5.2/lib/relaton_iso/scrapper.rb:309:in `fetch_title': undefined method `text' for nil:NilClass (NoMethodError)
bundler: failed to load command: metanorma (/Users/nickn/.rvm/gems/ruby-2.5.1/bin/metanorma)
NoMethodError: undefined method `text' for nil:NilClass
  /Users/nickn/.rvm/gems/ruby-2.5.1/gems/relaton-iso-0.5.2/lib/relaton_iso/scrapper.rb:309:in `fetch_title'
  /Users/nickn/.rvm/gems/ruby-2.5.1/gems/relaton-iso-0.5.2/lib/relaton_iso/scrapper.rb:141:in `block in fetch_titles_abstract'
  /Users/nickn/.rvm/gems/ruby-2.5.1/gems/relaton-iso-0.5.2/lib/relaton_iso/scrapper.rb:134:in `each'
  /Users/nickn/.rvm/gems/ruby-2.5.1/gems/relaton-iso-0.5.2/lib/relaton_iso/scrapper.rb:134:in `fetch_titles_abstract'
  /Users/nickn/.rvm/gems/ruby-2.5.1/gems/relaton-iso-0.5.2/lib/relaton_iso/scrapper.rb:61:in `parse_page'
  /Users/nickn/.rvm/gems/ruby-2.5.1/gems/relaton-iso-0.5.2/lib/relaton_iso/hit.rb:22:in `fetch'
  /Users/nickn/.rvm/gems/ruby-2.5.1/gems/relaton-iso-0.5.2/lib/relaton_iso/iso_bibliography.rb:85:in `block in fetch_pages'
  /Users/nickn/.rvm/gems/ruby-2.5.1/gems/relaton-bib-0.2.3/lib/relaton_bib/workers_pool.rb:19:in `block (2 levels) in worker'
make: *** [sources/cc-19160-6.xml] Error 1
````

Given that Relaton is not my code, this is going to be painful to debug.

**Comment by PeterTKY** [comment] 2019-08-13 06:22
I just updated the gems in the repo. Try bundle and then make and I think you will get the same results as me...

**Comment by opoudjis** [comment] 2019-08-13 06:23
I just have.

**Comment by PeterTKY** [comment] 2019-08-13 06:25
To be honest, until now I have no clear idea how to keep the related gems up-to-date in a consistent way.

**Comment by opoudjis** [comment] 2019-08-13 06:25
The crash is because a document identifier is *always* expected to be there. I will put in a work around, but this really looks like a problem in relaton. I will have the workaround issue a warning that it is making up a document identifier (the identifier it was supplied, in fact).

@andrew2net, ISO/IEC 10179 is not populating docidentifier, please investigate as well.

**Comment by opoudjis** [comment] 2019-08-13 06:27
@PeterTKY Metanorma/Relaton has grown into a monster, which is what happens with scope creep. @CAMOBAP795 has a task to automate our release process, which may mitigate things, but this is acute pain currently for all of us, as the stack remains under intense development.

**Comment by PeterTKY** [comment] 2019-08-13 06:35
I hope the automation will help. Currently I simply use the latest version in github for those heavily changing gems. But problems may arise if their versions are not compatible with each other...

**Comment by opoudjis** [comment] 2019-08-13 07:05
We're aware of that. Our approach has been to synchronise release of all gems at once, so that the published gems at least were internally consistent. But a bug fix in one will not be available until the next release (and you can't have both the  very latest bug fix and full integration testing simultaneously). Metanorma gem releases are every week to fortnight.

Now that relaton is managed separately, we've lost the synchronisation of those two stacks, but I do test relaton again when I do the metanorma releases.

**Comment by andrew2net** [comment] 2019-08-13 09:06
> @andrew2net, ISO/IEC 10179 is not populating docidentifier, please investigate as well.

@opoudjis seems the document page is changed, so `relaton-iso` needs to updated to parse the new page's format.

**Comment by ronaldtse** [comment] 2019-08-13 09:23
The issue is posted here now: https://github.com/metanorma/relaton-iso/issues/62

**Comment by ronaldtse** [comment] 2019-08-13 09:24
@opoudjis @PeterTKY in an unknowing fashion, today ISO.org's site has been updated -- rendering our data extraction mechanisms outdated. @andrew2net is fixing this as part of https://github.com/metanorma/relaton-iso/issues/62 .

**Comment by opoudjis** [comment] 2019-08-13 10:25
Implemented workaround: if the docidentifier is missing in the entry retrieved from Relaton, Metanorma will add a docidentifier to the entry, using the code it was passed to identify the entry, and it will issue an ERROR message. But this needs to be addressed in Relaton.

**Comment by ronaldtse** [comment] 2019-08-13 10:31
@opoudjis defensive programming is always good 👍  Thanks!

**Comment by opoudjis** [comment] 2019-08-13 10:50
The code is now crashing because the titles are not being retrieved either.

> @opoudjis @PeterTKY in an unknowing fashion, today ISO.org's site has been updated -- rendering our data extraction mechanisms outdated.

ISO has updated their site. 

Which is why screenscraping is a horrible idea, and production software cannot rely on it. @ronaldtse, I want you to give serious consideration to approaching ISO officially, and requesting a canonical listing of references.

**Comment by opoudjis** [comment] 2019-08-13 10:57
I'll do defensive coding for missing titles as well, substituting them with the original Asciidoctor provided text (and it's AUTOFILL, it's AUTOFILL). But this is a kluge to prevent crashing, and in cases like this, frankly, it's better to crash.

**Comment by andrew2net** [comment] 2019-08-13 11:10
@opoudjis `relaton-iso` is updated. Do we need to release it and `relaton` gems?

**Comment by opoudjis** [comment] 2019-08-13 11:29
Yes. This is emergency.

**Comment by opoudjis** [comment] 2019-08-13 11:34
I've stopped Metanorma crashing if the document identifiers and title are missing; and Andrej has just fixed the Relaton ISO screenscraper, to deal with their change in web format. I have just compiled the documents successfully, even though their content is currently going to be garbage. (All citations will have AUTOFILL as their title.) 

This ticket is about Metanorma's behaviour, as opposed to Andrej's fix. Therefore, this ticket is now closed.

**Closed by opoudjis** 2019-08-13 11:34 UTC
Labels: bug

**Comment by PeterTKY** [comment] 2019-08-14 02:35
> I'll do defensive coding for missing titles as well, substituting them with the original Asciidoctor provided text (and it's AUTOFILL, it's AUTOFILL). But this is a kluge to prevent crashing, and in cases like this, frankly, it's better to crash.

I think it may help at the moment if we can cache the results from successful scraping for example in Algolia (we are using I believe) or s3. In case there is some errors like this time, we can fallback to the cached results instead of having the compilation error.

**Comment by ronaldtse** [comment] 2019-08-14 02:36
@PeterTKY indeed, we're planning on doing this. Stay tuned...

**Comment by PeterTKY** [comment] 2019-08-14 03:53
But before that it sounds we have to fix the local caching mechanism first. As it always show "Local cache version is obsolete." right now and fetch in relation every time. Will post a new issue...

**Comment by ronaldtse** [comment] 2019-08-14 03:53
@PeterTKY right -- can you post at https://github.com/metanorma/relaton ? Thanks.
