### ISSUE TITLE
Equations get vanished when "Abbreviations" section is present

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#243] opened 2020-04-15 18:08 UTC
When "Abbreviations" section is present, the equations in the document don't show up.

*Code sample:*

````
== Symbols

[[tab-element-coordinate-axis-symbols]]
.Element coordinate axis symbols
[cols="2",options="header"]
|===
|Normalized axes |Definition of the coordinate system
|stem:[(xi,eta,zeta)] |an element parametric system
|stem:[(x,y,z)] |an element orthogonal system
|stem:[(x',y',z')] |an intermediate element orthogonal system (used in the derivation of an element orthogonal system)
|stem:[(X,Y,Z)] |a specified arbitrary system
|stem:[(i,j,k)] |the 2D analysis plane definition system
|===

[%unnumbered]
[stem]
++++
((1,,,,,,("symetric")),(2,n+1,,,,,),(3,n+2,2n,,,,),(*,*,*,3n-2,,,),(*,*,*,*,*,,),(*,*,*,*,*,*,),(n,2n-1,3n-3,*,*,*,n(n+1)//2))
++++
== Abbreviations

For the purposes of this part of ISO 10303, the following abbreviations apply.

DOF:: degree of freedom
FEA:: finite element analysis
ref:: reference
````
*Output (.doc):*
![capture1](https://user-images.githubusercontent.com/33627611/79371015-a9f0cb80-7f21-11ea-8682-c63f8b92347a.PNG)

Now, if we change the "Abbreviations" title for "Abbreviationss" (or whatever), we get:

*Output (.doc):*
![capture2](https://user-images.githubusercontent.com/33627611/79371027-b117d980-7f21-11ea-8b28-c4036791de2a.PNG)

This issue happens in the flavors: `iso` , `ogc`, `iec`, but not in `nist` nor `itu`. (I didn't test all the flavors though.) 

Thanks!

Sample file:
[issue-equations.zip](https://github.com/metanorma/metanorma-standoc/files/4482891/issue-equations.zip)

**Comment by ronaldtse** [comment] 2020-04-15 18:49
Is this the case for all equations, or only the equations in the Symbols section?

The Symbols/Abbreviations sections only allow "definition lists".

In any case this looks like some bug...

**Comment by manuel489** [comment] 2020-04-15 18:57
Well, according to my tests, for all the equations. The "Symbol" section is irrelevant, it could be any other section.

**Comment by opoudjis** [comment] 2020-04-25 11:27
The presence of Abbreviations is resulting in the MathML markup being stripped...

**Comment by opoudjis** [comment] 2020-04-25 11:33
https://github.com/metanorma/metanorma-iso/issues/338 has partly addressed this. Now maths is fine, but abbreviations are being ignored in output.

**Comment by opoudjis** [comment] 2020-04-25 11:34
Ah, that's... easy but nasty. ISO expects to find one `<symbols>` tag, and ignores a second: the sample document has `==Symbols`  then `==Abbreviations`.

So this issue is a duplicate of metanorma/metanorma-iso#338, and is now resolved.

**Closed by opoudjis** 2020-04-25 11:34 UTC
Labels: bug
