### ISSUE TITLE
Need functionality to format numbers

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#882] opened 2024-04-01 05:11 UTC
From metanorma/iso-2533#22

In ISO 2533 we have raw numbers coming from YAML like this:

`sources/iso-2533-2024/yaml/table7.yaml`:
```yaml
  - geometrical-altitude-m: -5000
    geometrical-altitude-ft: -16404
    geopotential-altitude-m: -5004
    geopotential-altitude-ft: -16417
    pressure-scale-height: 9371.8
    specific-weight: 18.968
    air-number-density: 4.0154e+25
    mean-speed: 484.15
    frequency: 11507000000.0
    mean-free-path: 4.2075e-08
```

And these numbers are rendered in the document, as plain text:

<img width="544" alt="Screenshot 2024-04-01 at 12 36 13" src="https://github.com/metanorma/iso-2533/assets/11865/9abd3660-2769-43c8-918c-14b223ad8cbe">

There are several problems with regards to number formatting:
1. I can't use `stem:[...]` because it would take forever in processing (Plurimath performance problem, MathML bloating problem in XML). For example, if all the numbers are in MathML, Safari can't even load the file due to MathJax having to render so many numbers.
2. These values are not formatted according to ISO 80000. This will be an editorial issue.
3. I can't choose the number format, e.g. if I wanted to shift the `e`, or if I wanted to shrink `11507000000.0` into something more manageable.

If we address these issues one by one:
1. We fix Plurimath. When it's just a number, we do not use MathML...? But if it has a unit, we need to UnitsML+MathML.
2. We implement an ISO 80000 profile for Plurimath-rendered plain numbers.
3. We implement some number formatting command...?

Thoughts needed.

**Comment by opoudjis** [comment] 2024-04-01 06:12
1. is already meant to have been implemented within Metanorma, in [https://github.com/metanorma/isodoc/blob/2d650f7788abf0eb14d89858c7877c3e36f927d3/lib/isodoc/presentation_function/math.rb#L102 :](https://github.com/metanorma/isodoc/blob/2d650f7788abf0eb14d89858c7877c3e36f927d3/lib/isodoc/presentation_function/math.rb#L129) : In Presentation XML, if a MathML consists of only an `mn` element, that expression is replaced by the contents of the `mn` element, so there is no longer a MathML expression to process. I will need to investigate why that is not happening here.

2. ISO 80000 rendering has already been brought up in https://github.com/metanorma/iso-iec-80000/issues/39 . There are two things to do. First, implement that rendering of numbers within Metanorma-ISO, as comparable rendering of numbers has already been implemented in BIPM and ITU. Second, outsource numbers rendering to Plurimath.

3. Number formatting can be implemented, and it would need to be triggered as some sort of TBD style directive on the stem wrapper around the MathML (make all numerals in this be styled according to some numeric style). That too can move to Plurimath, but I'd rather implement it locally first, and it will share code with the number localisation that inserts spaces currently.

**Comment by opoudjis** [comment] 2024-04-01 06:15
I will add that the resolution of numbers from MathML to strings happens in Presentation XML, not Semantic XML. If there are real processing issues already in the Semantic XML, I can do the conversion to strings earlier, in Semantic XML, but the insertion of spaces will still need to wait until Presentation XML, since it is specific to rendering.

**Comment by opoudjis** [comment] 2024-04-01 07:57
I've confirmed that MathML is stripped in Presentation XML if the expression contains only a single mn. So I need to see what is happening with ISO 2533 in particular.

ISO 80000 has been implemented. Moving it to Plurimath is delayed until I investigate why compiling ISO 2533 is so slow.

**Comment by opoudjis** [comment] 2024-04-01 11:17
Can't work out why there is a slowdown on iterating through admonition_anchor_names(), when example_anchor_names(), structurally identical, is instantaneous, and there are no admonitions in the text! Putting in a short-circuit to skip out if there are no admonitions in the clause, preempting recursing into subclauses.

**Comment by opoudjis** [comment] 2024-04-01 12:00
Turning to the stem:[]  marked up numbers in ISO 2533, I see why it's so slow: the stem:[] is converting from AsciiMath to MathML, 15 sec per 500 AsciiMath expressions, and there are 143k AsciiMath expressions in the marked up document. That means 70 mins to convert the AsciiMath. We don't want it, and we don't need it: I can detect numbers in AsciiMath, and convert them to MathML `mn` bypassing the Plurimath call.

**Comment by opoudjis** [comment] 2024-04-01 13:35
There is still a slowdown because of the large number of MathML numerals in the Semantic XML: 

Metanorma::Standoc::Cleanup#asciimath_parse : 18.8% of runtime, even with the short-circuiting of numerals in Metanorma Cleanup for conversion to MathML.
Metanorma::Standoc::Validate#math_validate : 17.6%
Metanorma::Standoc::Cleanup#mathml_cleanup : 6.5%

I'll see if I can shortcircuit some of these.

**Comment by opoudjis** [comment] 2024-04-01 13:46
Setting `m:math/@validate = false` for numeric-only MathML, to signal that MathML should skip validation.

Also going to skip mathml_cleanup() for those MathML expressions.

**Comment by opoudjis** [comment] 2024-04-01 14:16
>  ISO 2355 without number markup compiled in 11 mins (profiler time), is down to 7 mins. With number markup, it was blowing up PDF; Semantic XML converting MathML from AsciiMath was taking at least 1.5 hrs of real time; and Word was even slower. Now, it's 16 min of profiler time.

With these changes:

Semantic XML was taking 11 mins of real time, now it's 5 mins.
Was 16 min of profiler time for entire compilation (without PDF), now it's 11 mins.


1 and 2 are now done, and the document is now compiling in a more reasonable time. The remaining task is to somehow set the desired number formatting on these stem expressions, without undoing the current implementation of stem:[] ; it will require some novel markup.

**Comment by ronaldtse** [comment] 2024-04-01 17:15
`number:1337.982323[precision=3,format=# ##0.### ###]` is reasonable because it is analogous to `link:https://...[displaytext,options]`.

Maybe just `num:xxx`?

I'm still looking at `date:xxx` 😉

**Comment by opoudjis** [comment] 2024-04-02 00:06
`num:xxxx[]` not `number:[]`, you mean? Sure, why not.

There was an idiosyncratic scientific notation in ISO 2533 that you wanted supported: what was it? I'm worried about getting too creative with templates for scientific notation—twitter-cldr-rb is not particularly useful with its solitary "#E0", and I don't want to make stuff up; but there is a range of scientific notation that we need to support...

**Comment by opoudjis** [comment] 2024-04-02 02:37
For date, there is already https://github.com/metanorma/metanorma-standoc/issues/371 . We are using strftime format, and there is no reason to reinvent a well document preexisting formatting language like that.

**Comment by ronaldtse** [comment] 2024-04-02 03:36
"strftime format" means different things in different platforms and different languages... even on macOS and Linux.

**Comment by ronaldtse** [comment] 2024-04-02 03:37
And most of the time the entire document uses one date/number localization format, so maybe a per-document approach is also needed.

**Comment by opoudjis** [comment] 2024-04-02 06:33
There is already a per-document number-format spec, but I need to expand its scope anyway, because I don't think it will deal with the full range of possibilities for numeric format.

A strftime with multiple standards is still a hell of a lot better than us making up a brand new notation from scratch. And I have no problem with making Ruby's strftime the normative one. Also a lot better than the adhoccery of twitter-cldr-rb, which doesn't cover all cases, and which is not extensible the way they have implemented it.

**Comment by ronaldtse** [comment] 2024-04-02 06:36
@opoudjis sure, I actually did not remember that `date` was implemented. So any expanded documentation will be very useful.

**Comment by ronaldtse** [comment] 2024-04-02 06:42
And we don't support all ISO 8601 formats...

**Comment by opoudjis** [comment] 2024-04-02 10:33
> And we don't support all ISO 8601 formats...

Stop bringing me pointless objections. We support what ruby strftime supports, and anything ruby strftime does not support is a fictional edge case.


> And the syntax of `date[xxx]` is it better as `date:xxx[opts]`?

That would break things if we have used `date[]` anywhere, but I did only implement it last year. For backward compatibility:

* date:xxx[]
* date:xxx[opts]

would have to become the new default, and

* date[xxx] => date:xxx[]
* date[xxx,opts] => date:xxx[opts]

This is a ticket on number formatting. No further discussion on dates will be entertained here. You want more discussion on dates, AND A GENUINE USE CASE TO SUPPORT THAT DISCUSSION, then raise a separate ticket instead of distracting me with irrelevant discussion.

Anything that strftime does not support is overwhelmingly likely completely useless to standards documents anyway.

**Comment by opoudjis** [comment] 2024-04-02 10:37
This ticket is put on hold until https://github.com/plurimath/plurimath/issues/232 is realised.

When it is, the options in `num:value[opts]` will involve the various format parameters we are passing to the Plurimath call: locale, precision, digitcount, group, group_digits, decimal, fraction_group, fraction_group_digits, notation, exponent_sign, e

**Comment by ronaldtse** [comment] 2024-04-04 18:12
Re: `date` syntax. I don't know of any document currently using `date[...]` syntax.

https://github.com/search?q=org%3Ametanorma+%22+date%5B%22&type=code

**Comment by ronaldtse** [comment] 2024-06-20 11:19
@opoudjis so this task is unlocked because https://github.com/plurimath/plurimath/issues/232 is done.

**Comment by opoudjis** [comment] 2024-06-24 16:15
We do not currently support anything but straight decimal numbers currently in `number:[]`. Does `number:[]` need to read E notation too?

**Comment by ronaldtse** [comment] 2024-06-24 16:17
How will E notation look like?

**Comment by opoudjis** [comment] 2024-06-24 16:22
I dunno, I guess `number:4.134E31[]`. But we would have to insist on one format: no plus sign on exponent, and only `E` for the E-symbol.

**Comment by opoudjis** [comment] 2024-06-25 01:37
From @ronaldtse 

----

> `number:40154000000000000000000000[notation=e,exponent_sign=plus,precision=4]`. That will convert the number to 4.0145e+21.

This notation is quite crazy. Yes, you can do it with 1 number. With tables of numbers you're looking at extreme bloat.

## 1 To reduce bloat

Keep the single number format options. Add a document-wide number formatting mechanism, or define a display "profile" globally that the author can reuse in the document.

```adoc
:number-presentation: notation=e,exponent_sign=plus,precision=4
:number-presentation-profile: my_profile,notation=e,exponent_sign=plus,precision=6
...

number:40154000000000000000000000 // => 4.0145e+21 (using global profile)
number:40154000000000000000000000[profile=my_profile] // => 4.014500e+19 (using specific profile)
```

## 2 Simplify number entry

The format of `4.0154e+25` is already a Ruby number. There is no reason why we cannot use a reasonable notation for numbers since you can just use something like [this](https://stackoverflow.com/a/77287707) to parse numbers.

```adoc
:number-presentation: notation=e,exponent_sign=plus,precision=4

number:4.014500e+19 // => 4.0145e+21
```

## Plurimath display profile

And in fact, the problem is that we have not implemented a Plurimath render mode for ISO 80000...

cc @suleman-uzair

**Comment by opoudjis** [comment] 2024-06-25 01:40
Just shoving numbers info Integer() and Float() is the last thing we should be doing, because of the infinite precision requirements; this was a bug in Plurimath. The default is BigDecimal, and if that doesn't work for e-notation, I will need to regex it. There is absolutely a reason why I cannot just use something like Ronald is suggesting.

**Comment by ronaldtse** [comment] 2024-06-25 02:04
@opoudjis `BigDecimal(number)` works. The problem with BigDecimal is that it requires native compilation from Ruby 3.3 onwards...

**Comment by opoudjis** [comment] 2024-06-25 12:03
First, allowing E notation for numbers.

**Comment by opoudjis** [comment] 2024-06-25 13:12
We will process all arguments to number as BigDecimal, and output them in default exponent format in Semantic XML, e.g. `0.11e2`. We will exceptionally add any trailing zeroes after a decimal point as significant, unlike the built in behaviour of BigDecimal: `1100` will be 0.11e4, but `11.00` will be 0.1100e2.

On the isodoc Presentation XML side, if no precision is specified either on the number or as a document default, we will use the number of significant digits as the totaldigits for the number, so that 0.1100e2 will be rendered as 11.00.

**Comment by opoudjis** [comment] 2024-06-25 13:18
If no format argument has been passed to number:[], we will pass in notation=basic; that will force any exponential notation in math/mn to be converted back to basic notation.

**Comment by opoudjis** [comment] 2024-06-25 16:36
Lots of confusion happening because of Plurimath not coping with BigDecimal, and needing to keep default and guessed digit_count and precision from colliding. Almost resolved.

**Comment by opoudjis** [comment] 2024-06-26 03:14
Working OK for translating e-notation, but digit_count is not an acceptable substitute for significant digits, which I need to translate to and from e-notation correctly.

**Comment by opoudjis** [comment] 2024-06-27 10:25
We need to implement the profile commands as:

````
:number-presentation: notation=e,exponent_sign=plus,precision=4
:number-presentation-profile-my_profile: notation=e,exponent_sign=plus,precision=6
:number-presentation-profile-my_other_profile: notation=e,exponent_sign=plus,precision=6
...
````

Document attributes are unique, and reusing `:number-presentation-profile:` would overwrite all instances with the last.

The profiles need to be able to overwrite each other.

**Comment by opoudjis** [comment] 2024-06-27 13:03
And we need to able to set attributes to nil.

**Comment by opoudjis** [comment] 2024-06-27 13:05
Issue goes on hold until https://github.com/plurimath/plurimath/issues/264 is implemented.

**Comment by opoudjis** [comment] 2024-07-10 15:49
Plurimath is returning exponents in scientific/engineering notation in Ascii superscript, `1,00'00'00'0 × 10^+21`. I will need to convert that in postprocessing to either `<sup>` (when the number ends up outside of MathML) or `<msup><mn>...</mn><mn>...</mn></msup>` (when it remains within it).

**Closed** 2024-07-15 14:25 UTC
Labels: enhancement

**Comment by ronaldtse** [comment] 2024-07-16 07:01
> Plurimath is returning exponents in scientific/engineering notation in Ascii superscript, `1,00'00'00'0 × 10^+21`. I will need to convert that in postprocessing to either `<sup>` (when the number ends up outside of MathML) or `<msup><mn>...</mn><mn>...</mn></msup>` (when it remains within it).

Why does Metanorma have to do post-processing on Plurimath output?

**Comment by opoudjis** [comment] 2024-07-16 08:36
First because Plurimath is not wedded to Metanorma, it is its own gem, and it does not use Metanorma markup. Second, because Plurimath output may or may not end up inside of MathML.

Plurimath generates Asciimath as its numerical formatting output: `1,00'00'00'0 × 10^+21`.

That is a legitimate thing to be doing. And whatever happens, there will be conversion, since we do end up representing that two ways, in MathML, and outside of MathML.

We don't want numbers in isolation to be rendered as MathML at all; you know what happened when we did to the generated HTML. So we want `<math><mn>10 x 10^+21</mn></math>` would have to end up as `10 x 10<sup>+21</sup>`, which is not MathML. That absolutely is a matter of postprocessing.

You could argue that the numeric formatter should be natively exporting MathML, so it should be generating `<math><mrow><mn>10</mn><mo>x</mo> <sup><mn>10</mn><mn>+21</mn></msup></math>`.

I don't particularly care to make that argument, though, given how much of a pain in the ass it would be to convert that to  `10 x 10<sup>+21</sup>`.

You could also say that this postprocessing, to generate either MathML or Metanorma, should be happening within Plurimath. I do not agree that it should, because I don't agree that Metanorma markup has any place in Plurimath.

It's working, and it took a month to get it working. it is unnecessary to second-guess this, especially as this is all Presentation-level anyway.

**Comment by ronaldtse** [comment] 2024-07-16 08:56
I'm not exactly sure how this works, but:
* Plurimath's output is of many formats. For the value in HTML `10 x 10<sup>+21</sup>`, it should be able to output this in all its supported formats:
    * AsciiMath: `1,00'00'00'0 × 10^+21.` 
    * LaTeX: ...
    * HTML: `10 x 10<sup>+21</sup>`
    * OMML: ...
* `<math><mn>10 x 10^+21</mn></math>` is just broken MathML that should never be in the process.
* Plurimath also supports HTML output of math. If you want HTML math, you should directly ask it for that.

<img width="1090" alt="Screenshot 2024-07-16 at 4 55 05 PM" src="https://github.com/user-attachments/assets/6824f3f5-242f-4dfb-9fb3-c36ca5b0f54f">
