### ISSUE TITLE
Support newline in asciimath stem block

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#323] opened 2020-08-18 18:30 UTC
According to this thread https://github.com/asciidoctor/asciidoctor/issues/2497, a newline in stem block can be introduced using `\`. Nonetheless, Metanorma doesn't seem to support this approach.

````
[stem]
++++
A "and" B rarr [A&B] \
A "and" "ONEOF"(B1,B2) rarr A&[B1,B2] = [A&B1,A&B2] \
"ONEOF"(A1,A2) "and" "ONEOF"(B1,B2) rarr [A1,A2]&[B1,B2] = [A1&B1,A1&B2,A2&B1,A2&B2]
++++
````

Normal AsciiDoc:
![cap1](https://user-images.githubusercontent.com/33627611/90551332-2826de00-e15f-11ea-9b27-0c85bffc7ad5.PNG)

Metanorma (HTML):
![cap2](https://user-images.githubusercontent.com/33627611/90551344-2a893800-e15f-11ea-9df2-12125e3e1188.PNG)

Now, I can workaround this problem using inline stems:

````
stem:[A "and" B rarr [A&B\]] +
stem:[A "and" "ONEOF"(B1,B2) rarr A&[B1,B2\] = [A&B1,A&B2\]] +
stem:["ONEOF"(A1,A2) "and" "ONEOF"(B1,B2) rarr [A1,A2\]&[B1,B2\] = [A1&B1,A1&B2,A2&B1,A2&B2\]]
````
And the result will be practically the same as normal AsciiDoc, but I report the issue anyway.

Thanks!

**Comment by opoudjis** [comment] 2020-09-01 15:11
Duplicate of https://github.com/metanorma/metanorma-standoc/issues/111, and this is difficult.

**Closed** 2020-09-01 15:11 UTC
Labels: duplicate
